// src/components/AgentConfigModal.vue
<template>
  <transition name="modal">
    <div class="modal-mask" v-if="visible" @click.self="$emit('close')" @keydown.esc="$emit('close')">
      <div class="modal">
        <div class="modal-head">
          <div class="modal-title">
            <span class="modal-icon">{{ editing ? '✎' : '＋' }}</span>
            <h3>{{ editing ? '编辑 Agent' : '新建 Agent' }}</h3>
          </div>
          <button class="close-btn" @click="$emit('close')">✕</button>
        </div>

        <div class="modal-body">
          <div class="field-row">
            <label class="field grow">
              <span class="field-label">名称</span>
              <input v-model="form.name" placeholder="如：浏览器助手" />
            </label>
            <label class="field color-field">
              <span class="field-label">颜色</span>
              <input type="color" v-model="form.color" class="color-input" />
            </label>
          </div>

          <label class="field">
            <span class="field-label">模型</span>
            <select v-model="form.model">
              <option value="deepseek-v4-flash">deepseek-v4-flash（快速，默认）</option>
              <option value="deepseek-v4-pro">deepseek-v4-pro（更强推理）</option>
            </select>
          </label>

          <label class="field">
            <span class="field-label">系统提示词（persona）</span>
            <textarea v-model="form.persona" rows="4" placeholder="定义这个 Agent 的身份与行为…"></textarea>
          </label>

          <!-- 工具 -->
          <div class="field">
            <span class="field-label">工具（MCP Servers）</span>
            <div class="check-grid">
              <label
                v-for="srv in store.mcpServers"
                :key="srv.id"
                class="check-item"
                :class="{ checked: form.mcpServerIds.includes(srv.id) }"
              >
                <input type="checkbox" :value="srv.id" v-model="form.mcpServerIds" />
                <span class="check-icon">
                  <svg viewBox="0 0 16 16" width="11" height="11" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
                    <path d="M3 8.5l3.5 3.5L13 4.5" />
                  </svg>
                </span>
                <span class="check-name">{{ srv.name }}</span>
              </label>
              <span v-if="!store.mcpServers.length" class="empty-hint">无 MCP server 配置</span>
            </div>
          </div>

          <!-- 技能 -->
          <div class="field">
            <div class="field-head">
              <span class="field-label">技能（Skills）</span>
              <span class="field-count">{{ form.skillIds.length }} 已选</span>
            </div>
            <input
              v-model="skillSearch"
              class="search-input"
              placeholder="搜索技能…"
            />
            <div class="check-grid skill-grid">
              <label
                v-for="skill in filteredSkills"
                :key="skill.id"
                class="check-item"
                :class="{ checked: form.skillIds.includes(skill.id) }"
                :title="skill.description"
              >
                <input type="checkbox" :value="skill.id" v-model="form.skillIds" />
                <span class="check-icon">
                  <svg viewBox="0 0 16 16" width="11" height="11" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
                    <path d="M3 8.5l3.5 3.5L13 4.5" />
                  </svg>
                </span>
                <span class="check-name">{{ skill.name }}</span>
              </label>
              <span v-if="!filteredSkills.length" class="empty-hint">
                {{ store.skills.length ? '没有匹配的技能' : '无技能配置' }}
              </span>
            </div>
          </div>
        </div>

        <div class="modal-foot">
          <button class="ghost-btn" @click="$emit('close')">取消</button>
          <button class="primary-btn" @click="save()">
            {{ editing ? '保存' : '创建' }}
          </button>
        </div>
      </div>
    </div>
  </transition>
</template>

<script lang="ts">
import Vue from 'vue'
import { useMainStore } from '../store'
import type { Agent } from '../types'

const PALETTE = ['#8b7bff', '#4d6bfe', '#38bdf8', '#34d399', '#fbbf24', '#f87171']

export default Vue.extend({
  name: 'AgentConfigModal',
  props: {
    visible: { type: Boolean, default: false },
    editingAgent: { type: Object as () => Agent | null, default: null },
  },
  data() {
    return {
      form: this.blankForm(),
      skillSearch: '',
    }
  },
  computed: {
    editing(): boolean {
      return Boolean(this.editingAgent)
    },
    store() {
      return useMainStore()
    },
    filteredSkills() {
      const q = this.skillSearch.trim().toLowerCase()
      if (!q) return this.store.skills
      return this.store.skills.filter(
        (s) => s.name.toLowerCase().includes(q) || s.description.toLowerCase().includes(q) || s.id.toLowerCase().includes(q),
      )
    },
  },
  watch: {
    visible(v: boolean) {
      if (v) {
        this.skillSearch = ''
        if (this.editingAgent) {
          this.form = {
            name: this.editingAgent.name,
            model: this.editingAgent.model,
            persona: this.editingAgent.persona,
            mcpServerIds: [...this.editingAgent.mcpServerIds],
            skillIds: [...this.editingAgent.skillIds],
            color: this.editingAgent.color,
          }
        } else {
          this.form = this.blankForm()
        }
      }
    },
  },
  methods: {
    blankForm() {
      return {
        name: '',
        model: 'deepseek-v4-flash',
        persona: 'You are a helpful assistant. 用中文回答。',
        mcpServerIds: [] as string[],
        skillIds: [] as string[],
        color: PALETTE[Math.floor(Math.random() * PALETTE.length)],
      }
    },
    async save() {
      if (!this.form.name.trim()) {
        this.form.name = '未命名 Agent'
      }
      if (this.editingAgent) {
        await this.store.updateAgent(this.editingAgent.id, this.form)
      } else {
        await this.store.createAgent(this.form)
      }
      this.$emit('close')
    },
  },
})
</script>

<style scoped>
.modal-mask {
  position: fixed;
  inset: 0;
  background: rgba(5, 8, 15, 0.6);
  backdrop-filter: blur(6px);
  -webkit-backdrop-filter: blur(6px);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 1000;
}
.modal {
  width: 560px;
  max-height: 84vh;
  display: flex;
  flex-direction: column;
  background: rgba(17, 21, 32, 0.92);
  border: 1px solid var(--border-strong);
  border-radius: 20px;
  box-shadow: 0 24px 80px rgba(0, 0, 0, 0.55), inset 0 1px 0 rgba(255, 255, 255, 0.06);
  backdrop-filter: blur(24px);
  -webkit-backdrop-filter: blur(24px);
  animation: scaleIn 0.24s var(--ease-spring);
  overflow: hidden;
}
.modal-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 18px 22px;
  border-bottom: 1px solid var(--border);
}
.modal-title { display: flex; align-items: center; gap: 10px; }
.modal-icon {
  width: 30px;
  height: 30px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 9px;
  background: var(--grad-brand-soft);
  color: var(--brand);
  font-size: 15px;
  font-weight: 700;
}
.modal-head h3 { font-size: 16px; font-weight: 700; }
.close-btn {
  border: none;
  background: transparent;
  cursor: pointer;
  font-size: 14px;
  color: var(--text-faint);
  width: 28px;
  height: 28px;
  border-radius: 8px;
  transition: all 0.2s;
}
.close-btn:hover { background: var(--bg-card-hover); color: var(--text); }

.modal-body {
  padding: 18px 22px;
  overflow-y: auto;
  display: flex;
  flex-direction: column;
  gap: 16px;
}
.field-row { display: flex; gap: 14px; }
.field { display: flex; flex-direction: column; gap: 7px; }
.field.grow { flex: 1; }
.color-field { width: 86px; }
.field-label { font-size: 11px; font-weight: 600; color: var(--text-faint); letter-spacing: 0.08em; text-transform: uppercase; }
.field input[type='text'], .field input:not([type]), .field select, .field textarea {
  border: 1px solid var(--border);
  border-radius: var(--radius-sm);
  padding: 9px 12px;
  font-size: 13px;
  font-family: inherit;
  background: var(--bg-input);
  color: var(--text);
  outline: none;
  transition: all 0.2s var(--ease-out);
}
.field input:focus, .field input:not([type]):focus, .field select:focus, .field textarea:focus {
  border-color: rgba(109, 139, 255, 0.5);
  box-shadow: 0 0 0 3px rgba(109, 139, 255, 0.12);
}
.field input::placeholder, .field textarea::placeholder { color: var(--text-faint); }
select option { background: #141824; color: var(--text); }

/* 技能区：搜索 + 计数 + 限高滚动 */
.field-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
}
.field-count {
  font-size: 11px;
  color: var(--brand);
  background: rgba(109, 139, 255, 0.12);
  padding: 1px 8px;
  border-radius: 999px;
}
.search-input {
  border: 1px solid var(--border);
  border-radius: var(--radius-sm);
  padding: 8px 12px;
  font-size: 13px;
  font-family: inherit;
  background: var(--bg-input);
  color: var(--text);
  outline: none;
  transition: all 0.2s var(--ease-out);
}
.search-input:focus {
  border-color: rgba(109, 139, 255, 0.5);
  box-shadow: 0 0 0 3px rgba(109, 139, 255, 0.12);
}
.skill-grid {
  max-height: 220px;
  overflow-y: auto;
  padding: 2px;
}
.skill-grid::-webkit-scrollbar { width: 6px; }
.color-input {
  width: 100%;
  height: 36px;
  border: 1px solid var(--border);
  border-radius: var(--radius-sm);
  padding: 3px;
  cursor: pointer;
  background: var(--bg-input);
  -webkit-appearance: none;
  appearance: none;
}
.color-input::-webkit-color-swatch-wrapper { padding: 2px; }
.color-input::-webkit-color-swatch { border: none; border-radius: 6px; }
.color-input::-moz-color-swatch { border: none; border-radius: 6px; }

/* 勾选 pill */
.check-grid { display: flex; flex-wrap: wrap; gap: 8px; }
.check-item {
  display: inline-flex;
  align-items: center;
  gap: 7px;
  padding: 7px 13px;
  border: 1px solid var(--border);
  border-radius: 999px;
  font-size: 12px;
  cursor: pointer;
  transition: all 0.22s var(--ease-spring);
  color: var(--text-dim);
  background: transparent;
  user-select: none;
}
.check-item:hover { border-color: var(--border-strong); color: var(--text); transform: translateY(-1px); }
.check-item.checked {
  background: var(--grad-brand-soft);
  border-color: rgba(109, 139, 255, 0.45);
  color: var(--text);
  box-shadow: 0 2px 12px rgba(77, 107, 254, 0.15);
}
.check-item input { display: none; }
.check-icon {
  width: 15px;
  height: 15px;
  border-radius: 50%;
  border: 1.5px solid var(--border-strong);
  display: flex;
  align-items: center;
  justify-content: center;
  color: transparent;
  transition: all 0.2s var(--ease-spring);
}
.check-item.checked .check-icon {
  background: var(--grad-brand);
  border-color: transparent;
  color: #fff;
  transform: scale(1.08);
}
.check-name { font-weight: 500; }
.empty-hint { font-size: 12px; color: var(--text-faint); }

.modal-foot {
  display: flex;
  justify-content: flex-end;
  gap: 10px;
  padding: 16px 22px;
  border-top: 1px solid var(--border);
  background: rgba(255, 255, 255, 0.02);
}
.ghost-btn {
  border: 1px solid var(--border);
  background: transparent;
  color: var(--text-dim);
  padding: 9px 20px;
  border-radius: 11px;
  cursor: pointer;
  font-size: 13px;
  font-weight: 500;
  transition: all 0.2s var(--ease-out);
}
.ghost-btn:hover { background: var(--bg-card-hover); color: var(--text); }
.primary-btn {
  border: none;
  background: var(--grad-brand);
  color: #fff;
  padding: 9px 24px;
  border-radius: 11px;
  cursor: pointer;
  font-size: 13px;
  font-weight: 600;
  box-shadow: 0 3px 16px rgba(77, 107, 254, 0.35);
  transition: all 0.25s var(--ease-spring);
}
.primary-btn:hover { transform: translateY(-1px); box-shadow: 0 6px 24px rgba(77, 107, 254, 0.5); }
.primary-btn:active { transform: scale(0.97); }
</style>

// src/components/AgentConfigModal.tsx
import { useEffect, useState } from 'react'
import { AlertTriangle } from 'lucide-react'
import { useMainStore } from '../store'
import { Button } from './ui/button'
import { Input, Textarea } from './ui/input'
import { Label } from './ui/label'
import { Checkbox } from './ui/checkbox'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from './ui/dialog'
import { cn } from '../lib/utils'
import type { Agent } from '../types'

const PALETTE = ['#4d6bfe', '#8b7bff', '#38bdf8', '#34d399', '#fbbf24', '#f87171', '#f472b6', '#22d3ee']

interface Props {
  visible: boolean
  editingAgent: Agent | null
  onClose: () => void
}

interface FormState {
  name: string
  model: string
  persona: string
  mcpServerIds: string[]
  skillIds: string[]
  color: string
}

export default function AgentConfigModal({ visible, editingAgent, onClose }: Props) {
  const store = useMainStore()
  const [form, setForm] = useState<FormState>({ name: '', model: '', persona: '', mcpServerIds: [], skillIds: [], color: PALETTE[0] })
  const [formProvider, setFormProvider] = useState('')
  const [formModelId, setFormModelId] = useState('')
  const [skillSearch, setSkillSearch] = useState('')
  const [saving, setSaving] = useState(false)

  const editing = Boolean(editingAgent)
  const currentProvider = store.models.find((p) => p.id === formProvider)
  const currentModels = currentProvider?.models ?? []
  // 所选渠道未配置 key（项目外文件或环境变量都没有）时提示
  const providerNoKey = currentProvider ? (store.providerKeyStatus[formProvider] ?? 'none') === 'none' : false

  const filteredSkills = skillSearch.trim()
    ? store.skills.filter((s) => s.name.toLowerCase().includes(skillSearch.toLowerCase()) || s.description.toLowerCase().includes(skillSearch.toLowerCase()) || s.id.toLowerCase().includes(skillSearch.toLowerCase()))
    : store.skills

  // 打开时初始化表单
  useEffect(() => {
    if (!visible) return
    setSkillSearch('')
    if (editingAgent) {
      setForm({
        name: editingAgent.name,
        model: editingAgent.model,
        persona: editingAgent.persona,
        mcpServerIds: [...editingAgent.mcpServerIds],
        skillIds: [...editingAgent.skillIds],
        color: editingAgent.color,
      })
    } else {
      setForm({ name: '', model: store.defaultModelId(), persona: 'You are a helpful assistant. 用中文回答。', mcpServerIds: [], skillIds: [], color: PALETTE[Math.floor(Math.random() * PALETTE.length)] })
    }
  }, [visible, editingAgent])

  // 解析 form.model → provider + modelId
  useEffect(() => {
    if (!visible) return
    const providers = store.models
    if (!providers.length) return
    const slash = form.model.indexOf('/')
    let pid = slash > 0 ? form.model.slice(0, slash) : ''
    let mid = slash > 0 ? form.model.slice(slash + 1) : form.model
    if (!pid) {
      const hit = providers.find((p) => p.models.some((m) => m.id === mid))
      if (hit) pid = hit.id
      // 找不到匹配 provider：保留空（保存时用原 form.model，不做静默覆盖）
    }
    // 校验 provider 存在且包含该模型；不匹配则置空选择（防止保存时静默覆盖）
    const provider = providers.find((p) => p.id === pid)
    if (!provider || !provider.models.some((m) => m.id === mid)) {
      pid = ''
      mid = ''
    }
    setFormProvider(pid)
    setFormModelId(mid)
  }, [visible, form.model, store.models])

  const save = async () => {
    // 若模型选择无效（原模型不在注册表且用户未改），保留原 form.model
    const finalForm = { ...form, model: formProvider && formModelId ? `${formProvider}/${formModelId}` : form.model }
    setSaving(true)
    try {
      if (editingAgent) {
        await store.updateAgent(editingAgent.id, finalForm)
      } else {
        await store.createAgent(finalForm)
      }
      onClose()
    } finally {
      setSaving(false)
    }
  }

  return (
    <Dialog open={visible} onOpenChange={(open) => { if (!open) onClose() }}>
      <DialogContent className="max-h-[84vh] max-w-xl overflow-y-auto">
        <DialogHeader>
          <DialogTitle>{editing ? '编辑 Agent' : '新建 Agent'}</DialogTitle>
          <DialogDescription>配置助手的人设、模型、工具与技能</DialogDescription>
        </DialogHeader>

        <div className="flex flex-col gap-3.5">
          <div className="grid grid-cols-[1fr_70px] gap-3">
            <div className="flex flex-col gap-1.5">
              <Label>名称</Label>
              <Input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="如：浏览器助手" autoComplete="off" />
            </div>
            <div className="flex flex-col gap-1.5">
              <Label>颜色</Label>
              <input
                type="color"
                value={form.color}
                onChange={(e) => setForm({ ...form, color: e.target.value })}
                className="h-9 w-full cursor-pointer rounded-lg border border-border bg-input p-1"
              />
            </div>
          </div>

          {/* 模型两级选择 */}
          <div className="flex flex-col gap-1.5">
            <Label>模型</Label>
            <div className="grid grid-cols-[46%_1fr] gap-2">
              <select
                value={formProvider}
                onChange={(e) => {
                  const p = store.models.find((x) => x.id === e.target.value)
                  setFormProvider(e.target.value)
                  setFormModelId(p?.models[0]?.id ?? '')
                }}
                className="h-9 rounded-lg border border-border bg-input px-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-primary/40"
              >
                {store.models.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}
              </select>
              <select
                value={formModelId}
                onChange={(e) => setFormModelId(e.target.value)}
                className="h-9 rounded-lg border border-border bg-input px-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-primary/40"
              >
                {currentModels.map((m) => <option key={m.id} value={m.id}>{m.name || m.id}</option>)}
              </select>
            </div>
            {currentProvider?.baseUrl && (
              <p className="text-[11px] text-muted-foreground">服务地址：<code className="rounded bg-primary/10 px-1 font-mono text-primary">{currentProvider.baseUrl}</code></p>
            )}
            {providerNoKey && (
              <p className="flex items-start gap-1 rounded-lg border border-warning/30 bg-warning/10 px-2.5 py-1.5 text-[11px] text-warning">
                <AlertTriangle className="mr-1 inline h-3.5 w-3.5 flex-none" />
                该渠道尚未配置 API Key，调用会失败。请先到「模型渠道」页填写 {formProvider} 的 key。
              </p>
            )}
          </div>

          <div className="flex flex-col gap-1.5">
            <Label>系统提示词（persona）</Label>
            <Textarea rows={3} value={form.persona} onChange={(e) => setForm({ ...form, persona: e.target.value })} placeholder="定义这个 Agent 的身份与行为…" />
          </div>

          {/* 工具 */}
          <div className="flex flex-col gap-2">
            <Label>工具（MCP Servers）</Label>
            <div className="grid grid-cols-2 gap-2">
              {store.mcpServers.map((srv) => {
                const checked = form.mcpServerIds.includes(srv.id)
                return (
                  <label
                    key={srv.id}
                    className={cn(
                      'flex cursor-pointer items-center gap-2.5 rounded-xl border px-3 py-2.5 text-[13px] transition-all',
                      checked ? 'border-primary/35 bg-primary/10' : 'border-border bg-muted/30 hover:bg-muted',
                    )}
                  >
                    <Checkbox
                      checked={checked}
                      onCheckedChange={(v) => {
                        setForm({
                          ...form,
                          mcpServerIds: v
                            ? [...form.mcpServerIds, srv.id]
                            : form.mcpServerIds.filter((x) => x !== srv.id),
                        })
                      }}
                    />
                    <span className="font-medium">{srv.name}</span>
                  </label>
                )
              })}
              {!store.mcpServers.length && <div className="text-xs text-muted-foreground">暂无 MCP 服务器</div>}
            </div>
          </div>

          {/* 技能 */}
          <div className="flex flex-col gap-2">
            <Label>技能</Label>
            <Input value={skillSearch} onChange={(e) => setSkillSearch(e.target.value)} placeholder="搜索技能…" className="h-8 text-xs" />
            <div className="grid max-h-[180px] grid-cols-2 gap-2 overflow-y-auto pr-1">
              {filteredSkills.map((skill) => {
                const checked = form.skillIds.includes(skill.id)
                return (
                  <label
                    key={skill.id}
                    className={cn(
                      'flex cursor-pointer items-center gap-2.5 rounded-xl border px-3 py-2 text-[13px] transition-all',
                      checked ? 'border-primary/35 bg-primary/10' : 'border-border bg-muted/30 hover:bg-muted',
                    )}
                  >
                    <Checkbox
                      checked={checked}
                      onCheckedChange={(v) => {
                        setForm({
                          ...form,
                          skillIds: v ? [...form.skillIds, skill.id] : form.skillIds.filter((x) => x !== skill.id),
                        })
                      }}
                    />
                    <span className="truncate">{skill.name}</span>
                  </label>
                )
              })}
              {!filteredSkills.length && <div className="col-span-2 text-xs text-muted-foreground">没有匹配的技能</div>}
            </div>
          </div>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={onClose}>取消</Button>
          <Button onClick={() => void save()} disabled={!form.name.trim() || saving}>{editing ? '保存' : '创建'}</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
