// src/components/MainPane.vue
<template>
  <div class="main-pane">
    <header class="header" v-if="isChatView">
      <div class="header-left">
        <span class="agent-avatar" :style="{ '--accent': currentAgent?.color || '#6d8bff' }">
          {{ (currentAgent?.name || '?').charAt(0) }}
        </span>
        <div class="header-info">
          <span class="agent-name">{{ currentAgent?.name || '未选择 Agent' }}</span>
          <span class="agent-model">{{ currentAgent?.model || '' }}</span>
        </div>
      </div>
    </header>

    <header class="header" v-else>
      <div class="header-left">
        <span class="manager-tag">{{ view === 'skills' ? '📚' : view === 'tasks' ? '⏱️' : '🧰' }}</span>
        <div class="header-info">
          <span class="agent-name">{{ view === 'skills' ? '技能管理' : view === 'tasks' ? '定时任务' : '工具浏览' }}</span>
          <span class="agent-model">{{ view === 'skills' ? 'Skills' : view === 'tasks' ? 'Tasks' : 'Tools' }}</span>
        </div>
      </div>
    </header>

    <main class="pane-body">
      <transition name="view-fade" mode="out-in">
        <ChatView v-if="view === 'chat'" key="chat" />
        <TrajectoryView v-else-if="view === 'trajectory'" key="traj" />
        <SkillManager v-else-if="view === 'skills'" key="skills" />
        <TaskManager v-else-if="view === 'tasks'" key="tasks" />
        <ToolManager v-else key="tools" />
      </transition>
    </main>
  </div>
</template>

<script lang="ts">
import Vue from 'vue'
import { useMainStore } from '../store'
import ChatView from './ChatView.vue'
import TrajectoryView from './TrajectoryView.vue'
import SkillManager from './SkillManager.vue'
import TaskManager from './TaskManager.vue'
import ToolManager from './ToolManager.vue'

export default Vue.extend({
  name: 'MainPane',
  components: { ChatView, TrajectoryView, SkillManager, TaskManager, ToolManager },
  props: {
    view: { type: String, default: 'chat' },
  },
  computed: {
    store() {
      return useMainStore()
    },
    currentAgent() {
      return this.store.currentAgent
    },
    isChatView(): boolean {
      return this.view === 'chat' || this.view === 'trajectory'
    },
  },
})
</script>

<style scoped>
.main-pane {
  flex: 1;
  display: flex;
  flex-direction: column;
  min-width: 0;
  height: 100%;
}

/* Header */
.header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  height: 60px;
  padding: 0 24px;
  border-bottom: 1px solid var(--border);
  background: rgba(11, 14, 21, 0.5);
  backdrop-filter: blur(var(--blur));
  -webkit-backdrop-filter: blur(var(--blur));
  flex: none;
  z-index: 5;
}
.header-left { display: flex; align-items: center; gap: 12px; min-width: 0; }
.agent-avatar {
  width: 34px;
  height: 34px;
  border-radius: 11px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 15px;
  font-weight: 700;
  color: #fff;
  background: var(--grad-brand);
  box-shadow: 0 2px 14px rgba(77, 107, 254, 0.3);
}
.manager-tag { font-size: 20px; }
.header-info { display: flex; flex-direction: column; line-height: 1.25; }
.agent-name { font-weight: 600; font-size: 15px; }
.agent-model {
  font-size: 11px;
  color: var(--text-faint);
  font-family: var(--font-mono);
  letter-spacing: 0.02em;
}

/* Tab switch（胶囊切换） */
.tab-switch {
  display: flex;
  gap: 4px;
  padding: 4px;
  background: rgba(255, 255, 255, 0.05);
  border: 1px solid var(--border);
  border-radius: 12px;
}
.tab-btn {
  border: none;
  background: transparent;
  color: var(--text-dim);
  font-size: 13px;
  padding: 6px 14px;
  border-radius: 9px;
  cursor: pointer;
  display: flex;
  align-items: center;
  gap: 6px;
  transition: all 0.25s var(--ease-out);
  font-weight: 500;
}
.tab-btn:hover { color: var(--text); background: rgba(255, 255, 255, 0.06); }
.tab-btn.active {
  background: var(--grad-brand);
  color: #fff;
  box-shadow: 0 2px 14px rgba(77, 107, 254, 0.35);
}
.back-btn {
  border: 1px solid var(--border);
  background: transparent;
  color: var(--text-dim);
  padding: 7px 16px;
  border-radius: 10px;
  cursor: pointer;
  font-size: 13px;
  font-weight: 500;
  transition: all 0.22s var(--ease-out);
}
.back-btn:hover { background: var(--bg-card-hover); color: var(--text); }

.pane-body {
  flex: 1;
  min-height: 0;
  height: 100%;
  position: relative;
  overflow: hidden;
}
</style>

// src/components/MainPane.tsx
import { useMainStore } from '../store'
import ChatView from './ChatView'
import TrajectoryView from './TrajectoryView'
import SkillManager from './SkillManager'
import TaskManager from './TaskManager'
import ToolManager from './ToolManager'
import ModelChannels from './ModelChannels'

interface Props {
  view: string
  onNavigate: (view: string) => void
}

export default function MainPane({ view }: Props) {
  const agents = useMainStore((s) => s.agents)
  const currentAgentId = useMainStore((s) => s.currentAgentId)
  const currentModelLabel = useMainStore((s) => s.currentModelLabel())
  const currentAgent = agents.find((a) => a.id === currentAgentId)

  const isChatView = view === 'chat' || view === 'trajectory'
  const headerMeta: Record<string, { icon: string; title: string; sub: string }> = {
    models: { icon: '🧠', title: '模型渠道', sub: 'Model Providers' },
    skills: { icon: '📚', title: '技能管理', sub: 'Skills' },
    tasks: { icon: '⏱️', title: '定时任务', sub: 'Tasks' },
    tools: { icon: '🧰', title: '工具浏览', sub: 'Tools' },
  }
  const meta = headerMeta[view]

  return (
    <main className="flex h-full min-w-0 flex-1 flex-col">
      <header className="flex h-[60px] flex-none items-center border-b border-border bg-card/40 px-6 backdrop-blur-xl">
        {isChatView ? (
          <div className="flex items-center gap-3">
            <span
              className="flex h-8.5 w-8.5 items-center justify-center rounded-[11px] text-[15px] font-bold text-white shadow-[0_2px_14px_rgba(77,107,254,0.3)]"
              style={{ background: currentAgent?.color || '#6d8bff', width: 34, height: 34 }}
            >
              {(currentAgent?.name || '?').charAt(0)}
            </span>
            <div className="flex flex-col leading-tight">
              <span className="text-[15px] font-semibold">{currentAgent?.name || '未选择 Agent'}</span>
              {/* 模型切换已移到输入框工具栏（与同类产品一致）；这里只读展示 */}
              <span className="font-mono text-[11px] tracking-wide text-muted-foreground">{currentModelLabel || '未设置模型'}</span>
            </div>
          </div>
        ) : (
          <div className="flex items-center gap-3">
            <span className="text-xl">{meta?.icon}</span>
            <div className="flex flex-col leading-tight">
              <span className="text-[15px] font-semibold">{meta?.title}</span>
              <span className="font-mono text-[11px] tracking-wide text-muted-foreground">{meta?.sub}</span>
            </div>
          </div>
        )}
      </header>

      <div className="relative h-full min-h-0 flex-1 overflow-hidden">
        {view === 'chat' && <ChatView key="chat" />}
        {view === 'trajectory' && <TrajectoryView key="traj" />}
        {view === 'models' && <ModelChannels key="models" />}
        {view === 'skills' && <SkillManager key="skills" />}
        {view === 'tasks' && <TaskManager key="tasks" />}
        {view === 'tools' && <ToolManager key="tools" />}
      </div>
    </main>
  )
}
