// src/components/TrajectoryView.tsx
import { useState } from 'react'
import { ChevronDown, CheckCircle2, XCircle, Loader2, MessageSquare } from 'lucide-react'
import { useMainStore } from '../store'
import { cn } from '../lib/utils'
import type { ToolCallRecord } from '../types'

function fmtInput(input: unknown) {
  try { return JSON.stringify(input, null, 2) } catch { return String(input) }
}

function ToolInspector({ call }: { call: ToolCallRecord }) {
  const [open, setOpen] = useState(false)
  const [tab, setTab] = useState<'input' | 'output'>('input')
  return (
    <div className="overflow-hidden rounded-xl border border-border">
      <button
        className={cn(
          'flex w-full items-center gap-2 px-3 py-2 text-left text-xs',
          call.status === 'error' ? 'bg-destructive/5' : 'bg-muted/40',
        )}
        onClick={() => setOpen(!open)}
      >
        {call.status === 'running' && <Loader2 className="h-3.5 w-3.5 animate-spin text-warning" />}
        {call.status === 'success' && <CheckCircle2 className="h-3.5 w-3.5 text-success" />}
        {call.status === 'error' && <XCircle className="h-3.5 w-3.5 text-destructive" />}
        <span className="font-mono font-medium">{call.name}</span>
        <span className="flex-1 text-right text-[10px] text-muted-foreground">
          {call.status === 'running' ? '运行中' : `${(call.durationMs / 1000).toFixed(1)}s`}
        </span>
        <ChevronDown className={cn('h-3 w-3 text-muted-foreground transition-transform', open && 'rotate-180')} />
      </button>
      {open && (
        <div className="border-t border-border">
          <div className="flex gap-1 border-b border-border px-2 py-1">
            {(['input', 'output'] as const).map((t) => (
              <button
                key={t}
                className={cn('rounded-md px-2.5 py-0.5 text-[11px]', tab === t ? 'bg-primary/15 text-primary' : 'text-muted-foreground hover:text-foreground')}
                onClick={() => setTab(t)}
              >
                {t === 'input' ? '输入' : '输出'}
              </button>
            ))}
          </div>
          <pre className="max-h-[220px] overflow-auto bg-background/60 p-2.5 font-mono text-[11px] leading-relaxed">
            {tab === 'input' ? fmtInput(call.input) : call.output || '(空)'}
          </pre>
        </div>
      )}
    </div>
  )
}

export default function TrajectoryView() {
  const sessions = useMainStore((s) => s.sessions)
  const currentSessionId = useMainStore((s) => s.currentSessionId)
  const currentToolCalls = useMainStore((s) => s.currentToolCalls)
  const messages = sessions.find((s) => s.id === currentSessionId)?.messages ?? []

  const steps: Array<{ type: 'msg'; msg: typeof messages[number] } | { type: 'tool'; call: ToolCallRecord }> = []
  for (const m of messages) {
    if (m.toolCalls?.length) {
      for (const tc of m.toolCalls) steps.push({ type: 'tool', call: tc })
    }
    steps.push({ type: 'msg', msg: m })
  }
  for (const tc of currentToolCalls) steps.push({ type: 'tool', call: tc })

  const totalInput = messages.reduce((a, m) => a + (m.tokens?.input ?? 0), 0)
  const totalOutput = messages.reduce((a, m) => a + (m.tokens?.output ?? 0), 0)

  return (
    <div className="h-full overflow-y-auto px-8 py-7">
      <div className="mx-auto max-w-[760px]">
        <div className="mb-6">
          <h3 className="text-lg font-bold">轨迹视图</h3>
          <p className="mt-1 text-[13px] text-muted-foreground">
            本次对话共 {steps.length} 步 · Token：输入 {totalInput.toLocaleString()} / 输出 {totalOutput.toLocaleString()}
          </p>
        </div>

        <div className="relative flex flex-col gap-2.5 pl-5 before:absolute before:left-[5px] before:top-1 before:bottom-1 before:w-px before:bg-border">
          {steps.length === 0 && <div className="text-sm text-muted-foreground">还没有轨迹，先进行一段对话</div>}
          {steps.map((s, i) => (
            <div key={i} className="relative">
              <span
                className={cn(
                  'absolute -left-5 top-2 h-[11px] w-[11px] rounded-full border-2 border-background',
                  s.type === 'tool' ? (s.call.status === 'error' ? 'bg-destructive' : s.call.status === 'running' ? 'bg-warning' : 'bg-primary') : 'bg-muted-foreground/50',
                )}
              />
              {s.type === 'tool' ? (
                <ToolInspector call={s.call} />
              ) : (
                <div className={cn('flex items-center gap-2 rounded-xl border border-border px-3 py-2 text-xs', s.msg.role === 'user' ? 'bg-primary/5' : 'bg-card')}>
                  <MessageSquare className="h-3.5 w-3.5 flex-none opacity-60" />
                  <span className="flex-none font-medium">{s.msg.role === 'user' ? '用户' : '助手'}</span>
                  <span className="flex-1 truncate text-muted-foreground">{s.msg.content.slice(0, 80)}</span>
                  {s.msg.tokens && (
                    <span className="flex-none text-[10px] text-muted-foreground">
                      {s.msg.tokens.input.toLocaleString()} in / {s.msg.tokens.output.toLocaleString()} out
                    </span>
                  )}
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}

// src/components/TrajectoryView.vue
<template>
  <div class="trajectory">
    <div v-if="!events.length" class="empty">
      <div class="empty-orb"></div>
      <p>还没有轨迹数据。发一条消息触发工具调用，这里会展示每一步的输入 / 输出 / 耗时。</p>
    </div>

    <div v-else class="traj-body">
      <!-- 时间线 -->
      <div class="timeline">
        <div v-for="(ev, i) in events" :key="i" class="timeline-item" @click="selected = ev">
          <div class="tl-marker" :class="ev.kind">
            <span class="dot" :class="[ev.kind, ev.status]"></span>
            <span class="tl-line" v-if="i < events.length - 1"></span>
          </div>
          <div class="tl-content" :class="{ selected: selected === ev }">
            <div class="tl-title">
              <span v-if="ev.kind === 'turn'" class="tag turn">轮次</span>
              <span v-else-if="ev.kind === 'user'" class="tag user">用户</span>
              <span v-else-if="ev.kind === 'assistant'" class="tag assistant">助手</span>
              <span v-else class="tag tool">工具</span>
              <span class="tl-name">{{ ev.name }}</span>
              <span class="tl-meta" v-if="ev.durationMs != null">{{ fmtDuration(ev.durationMs) }}</span>
            </div>
            <div class="tl-preview" v-if="ev.preview">{{ ev.preview }}</div>
          </div>
        </div>
      </div>

      <!-- Inspector -->
      <div class="inspector" v-if="selected">
        <div class="inspector-head">
          <span class="tag" :class="selected.kind">{{ selected.kind }}</span>
          <span class="inspector-title">{{ selected.name }}</span>
          <button class="close-btn" @click="selected = null">✕</button>
        </div>
        <div class="inspector-body">
          <div v-if="selected.durationMs != null" class="kv">
            <span class="k">耗时</span>
            <span class="v">{{ fmtDuration(selected.durationMs) }}</span>
          </div>
          <div v-if="selected.tokens" class="kv">
            <span class="k">Token</span>
            <span class="v">{{ selected.tokens.input }} in / {{ selected.tokens.output }} out</span>
          </div>
          <div class="block" v-if="selected.input !== undefined">
            <div class="block-title">输入</div>
            <pre>{{ pretty(selected.input) }}</pre>
          </div>
          <div class="block" v-if="selected.output">
            <div class="block-title">输出</div>
            <pre>{{ selected.output }}</pre>
          </div>
          <div class="block" v-if="selected.content">
            <div class="block-title">内容</div>
            <pre>{{ selected.content }}</pre>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from 'vue'
import { useMainStore } from '../store'
import type { Message, ToolCallRecord } from '../types'

interface TrajEvent {
  kind: 'turn' | 'user' | 'assistant' | 'tool'
  name: string
  preview?: string
  status?: 'success' | 'error' | 'running'
  durationMs?: number
  tokens?: { input: number; output: number }
  input?: unknown
  output?: string
  content?: string
}

export default Vue.extend({
  name: 'TrajectoryView',
  data() {
    return { selected: null as TrajEvent | null }
  },
  computed: {
    store() {
      return useMainStore()
    },
    events(): TrajEvent[] {
      const messages: Message[] = this.store.currentSession?.messages ?? []
      const evs: TrajEvent[] = []
      for (let i = 0; i < messages.length; i++) {
        const m = messages[i]
        evs.push({
          kind: m.role === 'user' ? 'user' : 'assistant',
          name: m.role === 'user' ? '用户消息' : '助手回复',
          preview: m.content.slice(0, 60),
          content: m.content,
          tokens: m.tokens,
        })
        if (m.role === 'assistant' && m.toolCalls) {
          for (const tc of m.toolCalls) {
            evs.push(this.toolEvent(tc))
          }
        }
      }
      return evs
    },
  },
  methods: {
    toolEvent(tc: ToolCallRecord): TrajEvent {
      return {
        kind: 'tool',
        name: tc.name,
        preview: this.pretty(tc.input).slice(0, 60),
        status: tc.status,
        durationMs: tc.durationMs,
        input: tc.input,
        output: tc.output,
      }
    },
    pretty(v: unknown): string {
      try {
        return JSON.stringify(v, null, 2)
      } catch {
        return String(v)
      }
    },
    fmtDuration(ms: number): string {
      return ms >= 1000 ? `${(ms / 1000).toFixed(1)}s` : `${ms}ms`
    },
  },
})
</script>

<style scoped>
.trajectory { height: 100%; display: flex; flex-direction: column; }
.empty {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 14px;
  color: var(--text-dim);
  padding: 40px;
  text-align: center;
  position: relative;
  overflow: hidden;
}
.empty-orb {
  position: absolute;
  width: 320px;
  height: 320px;
  border-radius: 50%;
  background: radial-gradient(circle, rgba(139, 123, 255, 0.12), transparent 65%);
  filter: blur(16px);
}
.empty p { position: relative; max-width: 380px; font-size: 13px; }

.traj-body { flex: 1; display: flex; min-height: 0; }

/* 时间线 */
.timeline {
  flex: 1;
  overflow-y: auto;
  padding: 20px 24px;
  display: flex;
  flex-direction: column;
}
.timeline-item { display: flex; gap: 14px; cursor: pointer; }
.tl-marker { display: flex; flex-direction: column; align-items: center; padding-top: 8px; }
.dot {
  width: 10px;
  height: 10px;
  border-radius: 50%;
  flex: none;
  position: relative;
  z-index: 1;
}
.dot.success { background: var(--success); box-shadow: 0 0 8px rgba(52, 211, 153, 0.6); }
.dot.error { background: var(--danger); box-shadow: 0 0 8px rgba(248, 113, 113, 0.6); }
.dot.running { background: var(--running); box-shadow: 0 0 8px rgba(251, 191, 36, 0.7); animation: pulse 1.1s infinite; }
.dot.user, .dot.assistant, .dot.turn { background: var(--grad-brand); box-shadow: 0 0 8px rgba(109, 139, 255, 0.5); }
.tl-line {
  width: 2px;
  flex: 1;
  min-height: 20px;
  background: linear-gradient(180deg, rgba(255, 255, 255, 0.12), rgba(255, 255, 255, 0.04));
  margin: 2px 0;
}

.tl-content {
  flex: 1;
  min-width: 0;
  padding: 6px 10px;
  margin-bottom: 4px;
  border-radius: var(--radius-sm);
  transition: all 0.2s var(--ease-out);
  border: 1px solid transparent;
}
.tl-content:hover { background: var(--bg-card-hover); }
.tl-content.selected {
  background: var(--grad-brand-soft);
  border-color: rgba(109, 139, 255, 0.3);
}
.tl-title { display: flex; align-items: center; gap: 8px; font-size: 13px; }
.tag {
  font-size: 10px;
  padding: 1px 7px;
  border-radius: 6px;
  font-weight: 700;
  letter-spacing: 0.05em;
  text-transform: uppercase;
}
.tag.turn { background: rgba(139, 123, 255, 0.18); color: #a5b4fc; }
.tag.user { background: rgba(56, 189, 248, 0.16); color: #7dd3fc; }
.tag.assistant { background: rgba(52, 211, 153, 0.15); color: #6ee7b7; }
.tag.tool { background: rgba(251, 191, 36, 0.16); color: #fcd34d; }
.tl-name { font-weight: 600; }
.tl-meta { margin-left: auto; color: var(--text-faint); font-size: 11px; font-family: var(--font-mono); }
.tl-preview {
  color: var(--text-faint);
  font-size: 12px;
  margin-top: 2px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  max-width: 480px;
}

/* Inspector */
.inspector {
  width: 400px;
  flex: none;
  border-left: 1px solid var(--border);
  display: flex;
  flex-direction: column;
  background: rgba(11, 14, 21, 0.5);
  backdrop-filter: blur(14px);
  -webkit-backdrop-filter: blur(14px);
  animation: fadeIn 0.25s;
}
.inspector-head {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 14px 16px;
  border-bottom: 1px solid var(--border);
}
.inspector-title { font-weight: 600; font-size: 13px; flex: 1; font-family: var(--font-mono); }
.close-btn {
  border: none;
  background: transparent;
  cursor: pointer;
  color: var(--text-faint);
  width: 26px;
  height: 26px;
  border-radius: 7px;
  transition: all 0.2s;
}
.close-btn:hover { background: var(--bg-card-hover); color: var(--text); }
.inspector-body { flex: 1; overflow-y: auto; padding: 16px; display: flex; flex-direction: column; gap: 14px; }
.kv { display: flex; gap: 10px; font-size: 13px; }
.k { color: var(--text-faint); min-width: 50px; }
.v { font-weight: 600; font-family: var(--font-mono); font-size: 12px; }
.block-title { font-size: 10px; font-weight: 600; color: var(--text-faint); letter-spacing: 0.1em; text-transform: uppercase; margin-bottom: 6px; }
.block pre {
  font-family: var(--font-mono);
  font-size: 12px;
  background: rgba(11, 14, 21, 0.6);
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 10px;
  white-space: pre-wrap;
  word-break: break-word;
  max-height: 320px;
  overflow-y: auto;
  color: #d1d5db;
  line-height: 1.55;
}
</style>
