// src/App.tsx
import { useEffect, useState } from 'react'
import { useMainStore } from './store'
import Sidebar from './components/Sidebar'
import MainPane from './components/MainPane'
import AgentConfigModal from './components/AgentConfigModal'
import type { Agent } from './types'

export type View = 'chat' | 'trajectory' | 'skills' | 'tasks' | 'tools' | 'models'

export default function App() {
  const init = useMainStore((s) => s.init)
  const [view, setView] = useState<View>('chat')
  const [modalVisible, setModalVisible] = useState(false)
  const [editingAgent, setEditingAgent] = useState<Agent | null>(null)

  useEffect(() => {
    init().catch((e: Error) => {
      useMainStore.setState({ error: `初始化失败: ${e.message}（请确认后端已启动）` })
    })
  }, [init])

  const openCreate = () => { setEditingAgent(null); setModalVisible(true) }
  const openEdit = (agent: Agent) => { setEditingAgent(agent); setModalVisible(true) }
  const navigate = (v: string) => setView(v as View)

  return (
    <div className="flex h-full w-full overflow-hidden">
      <Sidebar
        view={view}
        onNewAgent={openCreate}
        onEditAgent={openEdit}
        onNavigate={navigate}
      />
      <MainPane view={view} onNavigate={navigate} />
      <AgentConfigModal visible={modalVisible} editingAgent={editingAgent} onClose={() => setModalVisible(false)} />
    </div>
  )
}

// src/App.vue
<template>
  <div id="app" class="app">
    <Sidebar :view="view" @new-agent="openCreate()" @edit-agent="openEdit" @open-key="keyModal = true" @navigate="view = $event" />
    <MainPane :view="view" @navigate="view = $event" />
    <AgentConfigModal :visible="modalVisible" :editing-agent="editingAgent" @close="modalVisible = false" />
    <ApiKeyModal :visible="keyModal" @close="keyModal = false" />
  </div>
</template>

<script lang="ts">
import Vue from 'vue'
import { useMainStore } from './store'
import Sidebar from './components/Sidebar.vue'
import MainPane from './components/MainPane.vue'
import AgentConfigModal from './components/AgentConfigModal.vue'
import ApiKeyModal from './components/ApiKeyModal.vue'
import type { Agent } from './types'

export default Vue.extend({
  name: 'App',
  components: { Sidebar, MainPane, AgentConfigModal, ApiKeyModal },
  data() {
    return {
      view: 'chat' as 'chat' | 'trajectory' | 'skills' | 'tools',
      modalVisible: false,
      keyModal: false,
      editingAgent: null as Agent | null,
    }
  },
  async mounted() {
    const store = useMainStore()
    try {
      await store.init()
    } catch (e) {
      store.error = `初始化失败: ${(e as Error).message}（请确认后端已启动）`
    }
  },
  methods: {
    openCreate() {
      this.editingAgent = null
      this.modalVisible = true
    },
    openEdit(agent: Agent) {
      this.editingAgent = agent
      this.modalVisible = true
    },
  },
})
</script>
